import pyautogui as py
import time as t
t.sleep(0.5)
py.press('winleft')
t.sleep(0.5)
py.write('edge')
t.sleep(0.5)
py.press('enter')
t.sleep(0.5)
py.hotkey('ctrl','shift','n')
t.sleep(0.5)
py.write('https://mail.google.com/mail/u/0/#inbox', interval=0.05)
py.press('enter')
t.sleep(3)
py.write('coloque seu email gmail', interval=0.05)
py.moveTo(1480,747)
t.sleep(0.5)
py.click()
t.sleep(4)
py.write('coloque sua senha gmail')
py.moveTo(1480,718)
t.sleep(0.5)
py.click()
t.sleep(20)
py.moveTo(121,251)
t.sleep(0.5)
py.click()
t.sleep(0.5)
py.move(755,478)
py.write('email para que voce quer enviar', interval=0.05)
t.sleep(0.5)
py.press('tab')
t.sleep(0.5)
py.press('tab')
t.sleep(0.5)
py.write('coloque o assunto')
t.sleep(0.5)
py.press('tab')
t.sleep(0.5)
py.write('coloque o assunto')
t.sleep(0.5)
py.press('enter')
t.sleep(0.5)
py.write('coloque o assunto', interval=0.05)
t.sleep(0.5)
py.press('tab')
t.sleep(0.5)
py.press('tab')
t.sleep(0.5)
py.press('tab')
t.sleep(0.5)
py.press('tab')
t.sleep(0.5)
py.press('enter')
t.sleep(0.5)
py.moveTo(468,80)
t.sleep(0.5)
py.click()
py.hotkey('ctrl','v')
t.sleep(0.5)
py.press('enter')
t.sleep(0.5)
py.moveTo(451,327)
py.click()
t.sleep(0.5)
py.press('enter')
t.sleep(0.5)
py.press('enter')
t.sleep(0.5)
py.press('tab')
t.sleep(0.5)
py.press('enter')
t.sleep(0.5)
py.hotkey('alt','F4')